version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_TELEMETRY_DISABLED=1
      - TAILWINDCSS_DEBUG=false
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PORT=8000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
    volumes:
      - ./.env:/app/.env:ro
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
    restart: unless-stopped # Removed the api service since it appears to be obsolete or misconfigured
networks:
  default:
    driver: bridge
